# Relatório de Análise IV

**Seleções e Frequências**

In [ ]:
import pandas as pd

In [18]:
df = pd.read_csv('/content/drive/MyDrive/bases_de_dados/aluguel_residencial.csv', sep=';')
df.head(10)

                 Tipo           Bairro  Quartos  ...    Valor  Condominio  IPTU
0           Quitinete       Copacabana        1  ...   1700.0       500.0  60.0
1                Casa  Jardim Botânico        2  ...   7000.0         NaN   NaN
2         Apartamento           Centro        1  ...    800.0       390.0  20.0
3         Apartamento     Higienópolis        1  ...    800.0       230.0   NaN
4         Apartamento     Vista Alegre        3  ...   1200.0         NaN   NaN
5         Apartamento         Cachambi        2  ...   1300.0       301.0  17.0
6  Casa de Condomínio  Barra da Tijuca        5  ...  22000.0         NaN   NaN
7  Casa de Condomínio            Ramos        2  ...   1000.0         NaN   NaN
8         Apartamento           Centro        1  ...   1200.0         NaN   NaN
9         Apartamento           Grajaú        2  ...   1500.0       642.0  74.0

[10 rows x 9 columns]

**Atividades**

*Selecione somente os imóveis classificados com tipo 'Apartamento'.*

In [ ]:
imovel_apartamento = df.query('Tipo == "Apartamento"')

# organizando os indices

def organiza_indice(dataset):
  dataset.index = range(len(dataset))
  return dataset

organiza_indice(imovel_apartamento)

              Tipo                Bairro  Quartos  ...   Valor  Condominio  IPTU
0      Apartamento                Centro        1  ...   800.0       390.0  20.0
1      Apartamento          Higienópolis        1  ...   800.0       230.0   NaN
2      Apartamento          Vista Alegre        3  ...  1200.0         NaN   NaN
3      Apartamento              Cachambi        2  ...  1300.0       301.0  17.0
4      Apartamento                Centro        1  ...  1200.0         NaN   NaN
...            ...                   ...      ...  ...     ...         ...   ...
19527  Apartamento        Vila Valqueire        2  ...  1000.0       550.0   NaN
19528  Apartamento                 Méier        2  ...   900.0       490.0  48.0
19529  Apartamento           Jacarepaguá        3  ...  1800.0       800.0  40.0
19530  Apartamento  São Francisco Xavier        2  ...  1400.0       509.0  37.0
19531  Apartamento                Leblon        2  ...  3000.0       760.0   NaN

[19532 rows x 9 columns]

*Selecione os imóveis classificados com tipos 'Casa', 'Casa de Condomínio' e 'Casa de Vila'.*

In [ ]:
# definindo os tipos solicitados
tipos_de_imoveis = ['Casa', 'Casa de Condomínio', 'Casa de Vila']

In [ ]:
# filtrando somente imóveis que fazem parte do conjunto 'tipos_de_imoveis'
imoveis_tipo_casa = df.query('Tipo in @tipos_de_imoveis')

# organizando os indices

organiza_indice(imoveis_tipo_casa)

                    Tipo                   Bairro  ...  Condominio    IPTU
0                   Casa          Jardim Botânico  ...         NaN     NaN
1     Casa de Condomínio          Barra da Tijuca  ...         NaN     NaN
2     Casa de Condomínio                    Ramos  ...         NaN     NaN
3     Casa de Condomínio                  Taquara  ...         NaN     NaN
4     Casa de Condomínio          Barra da Tijuca  ...      2695.0     NaN
...                  ...                      ...  ...         ...     ...
2207  Casa de Condomínio  Freguesia (Jacarepaguá)  ...       530.0  1250.0
2208                Casa            Bento Ribeiro  ...         NaN     NaN
2209  Casa de Condomínio          Barra da Tijuca  ...      3000.0     NaN
2210                Casa                   Centro  ...         NaN    80.0
2211  Casa de Condomínio          Barra da Tijuca  ...      1711.0  2332.0

[2212 rows x 9 columns]

*Selecione os imóveis com área entre 60 e 100 metros quadrados, incluindo os limites.*

In [ ]:
areas_60_a_100 = df.query('Area >= 60 and Area <= 100')

# organizando os indices

organiza_indice(areas_60_a_100)

                    Tipo                    Bairro  ...  Condominio   IPTU
0                   Casa           Jardim Botânico  ...         NaN    NaN
1            Apartamento              Vista Alegre  ...         NaN    NaN
2     Casa de Condomínio                     Ramos  ...         NaN    NaN
3            Apartamento                    Grajaú  ...       642.0   74.0
4            Apartamento       Lins de Vasconcelos  ...       455.0   14.0
...                  ...                       ...  ...         ...    ...
8714         Apartamento  Recreio dos Bandeirantes  ...       790.0    NaN
8715         Apartamento                    Leblon  ...      1010.0  249.0
8716         Apartamento                     Méier  ...       490.0   48.0
8717         Apartamento               Jacarepaguá  ...       800.0   40.0
8718         Apartamento                    Leblon  ...       760.0    NaN

[8719 rows x 9 columns]

*Selecione os imóveis que tenham pelo menos 4 quartos e aluguel menor que R$ 2.000,00.*

In [ ]:
imoveis_4_quartos_abaixo_2000 = df.query('Quartos >= 4 and Valor < 2000')

# organizando os indices

organiza_indice(imoveis_4_quartos_abaixo_2000)

                  Tipo                    Bairro  ...  Condominio   IPTU
0          Apartamento  Recreio dos Bandeirantes  ...       830.0    NaN
1          Apartamento                   Taquara  ...         NaN    NaN
2                 Casa              Campo Grande  ...         NaN    NaN
3                 Casa         Engenho de Dentro  ...         NaN    NaN
4          Apartamento  Recreio dos Bandeirantes  ...         NaN   90.0
5         Casa de Vila                     Méier  ...         NaN    NaN
6                 Casa              Campo Grande  ...         NaN    NaN
7          Apartamento              Campo Grande  ...       500.0    NaN
8          Apartamento  Recreio dos Bandeirantes  ...      1492.0  205.0
9          Apartamento               Cidade Nova  ...         NaN    NaN
10         Apartamento                 Pechincha  ...      1100.0  270.0
11                Casa                 Riachuelo  ...         NaN   40.0
12                Casa                     Méier  ...         NaN    NaN
13         Apartamento  Recreio dos Bandeirantes  ...      1400.0  580.0
14         Apartamento  Recreio dos Bandeirantes  ...      1380.0  700.0
15         Apartamento  Recreio dos Bandeirantes  ...      1093.0  183.0
16         Apartamento  Recreio dos Bandeirantes  ...      1038.0  158.0
17  Casa de Condomínio                   Taquara  ...       550.0  993.0
18                Casa              Santo Cristo  ...         NaN    NaN
19         Apartamento                      Leme  ...      2000.0  270.0
20         Apartamento  Recreio dos Bandeirantes  ...       930.0  150.0
21         Apartamento                   Camorim  ...       747.0    NaN
22         Apartamento           Barra da Tijuca  ...      1766.0    NaN
23                Casa                Praça Seca  ...         NaN  228.0
24  Casa de Condomínio   Freguesia (Jacarepaguá)  ...       195.0   30.0
25                Casa        Pedra de Guaratiba  ...         NaN    NaN
26         Apartamento              Campo Grande  ...       880.0    NaN
27         Apartamento  Recreio dos Bandeirantes  ...       912.0  160.0
28         Apartamento              Rio Comprido  ...       500.0    NaN
29                Casa              Campo Grande  ...         NaN    NaN
30         Apartamento                   Taquara  ...         NaN    NaN
31                Casa              Campo Grande  ...         NaN  208.0
32                Casa              Campo Grande  ...         NaN    NaN
33                Casa              Braz de Pina  ...         NaN    NaN
34                Casa              Campo Grande  ...         NaN    NaN
35                Casa              Campo Grande  ...       300.0    NaN
36         Apartamento              Campo Grande  ...       950.0    NaN
37         Apartamento           Barra da Tijuca  ...      1600.0  196.0
38         Apartamento             Vargem Grande  ...         NaN  176.0
39         Apartamento  Recreio dos Bandeirantes  ...      1038.0    NaN
40                Casa              Campo Grande  ...         NaN    NaN

[41 rows x 9 columns]